"""events

Revision ID: 866728df089c
Revises: 4f278a4054a2
Create Date: 2025-01-16 10:35:30.884350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866728df089c'
down_revision = '4f278a4054a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))
        batch_op.alter_column('family_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_events_owner_adults'), 'adults', ['owner'], ['id'])
        batch_op.drop_column('member_id')
        batch_op.drop_column('member_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_type', sa.VARCHAR(length=5), nullable=False))
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_events_owner_adults'), type_='foreignkey')
        batch_op.alter_column('family_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
